[package]
name = "branch"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
mlua = { version = "0.9.6", features = ["luajit"] }
