[package]
name = "branch"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
strip = true
lto = true
panic = "abort"

[dependencies]
anyhow = "1.0.80"
branch-macro = { path = "branch-macro" }
clap = { version = "4.5.1", features = ["derive"] }
mlua = { version = "0.9.6", features = ["luajit", "vendored"] }
