name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libluajit-5.1-dev
    - name: Check
      run: |
        cargo fmt --check
        cargo clippy
    - name: Build
      run: |
        cargo build --verbose
